# Generated by Django 2.0.13 on 2019-03-31 06:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readnum',
            options={'verbose_name': '阅读统计', 'verbose_name_plural': '阅读统计'},
        ),
        migrations.AlterModelTable(
            name='readnum',
            table='readnum',
        ),
    ]
