# Generated by Django 2.0.13 on 2019-03-30 03:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-last_updated', '-created_time'], 'verbose_name': '博客', 'verbose_name_plural': '博客'},
        ),
    ]
